# Generated by Django 3.2.15 on 2022-11-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20221029_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='recieveruser',
            new_name='reciever_user',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='senderuser',
            new_name='sender_user',
        ),
    ]
