# Generated by Django 3.2.15 on 2022-12-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_chatroom'),
        ('recommender', '0005_notification'),
    ]

    operations = [
    ]
