# Generated by Django 3.2.15 on 2022-12-11 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_merge_0003_chatroom_0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.TextField()),
                ('track_name', models.TextField()),
                ('track_album_id', models.TextField()),
                ('track_album_name', models.TextField()),
                ('track_genre', models.TextField(default='')),
                ('album_cover', models.TextField()),
                ('artist_name', models.TextField()),
                ('release_date', models.TextField()),
                ('preview_url', models.TextField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='post',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='music',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recommender.musicdata'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post', 'value')},
            },
        ),
    ]
