# Generated by Django 3.2.15 on 2022-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_auto_20221211_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdata',
            name='artist_id',
            field=models.TextField(default=''),
        ),
    ]
