# Generated by Django 3.2.15 on 2022-12-13 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_musicdata_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='album',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='genres',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='friends_list',
            field=models.ManyToManyField(related_name='_recommender_user_friends_list_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
