# Generated by Django 3.2.15 on 2022-12-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_alter_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='spotify_ref_id',
            field=models.CharField(default=None, max_length=228, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
